---
title: "Домашнее задание по теории вероятностей №2, задание 4"
author: "Олег Тарасов"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)

library(ggplot2)
library(dplyr)
library(tidyr)
library(tibble)

```

## Задаем истинную вероятность
```{r population}

true_prob <- 0.5 # Истинная вероятность

print(true_prob)
```
## Однократная оценка по выборке

```{r sample_1}

n_patients_1 <- 5 # Количество добровольцев 

my_group <- rbinom(n_patients_1, 1, true_prob) # Результаты добровольцев
print(my_group)

sample_prob_1 <- sum(my_group)/length(my_group)
print(sample_prob_1)

```

## Набираем статистику

```{r sample_n}

n_patients <- 5 # Количество добровольцев 

n_repeats <- 1000 # Количество повторений эксперимента

df_all_repeats <- data.frame(
  n_exp = rep(1:n_repeats, each = n_patients),
  ID = rep(1:n_patients, n_repeats),
  success = rbinom(n_repeats*n_patients, 1, true_prob)
)

```

## Оценка вероятности в каждом эксперименте

```{r estimations, fig.width=8, fig.height=4}

df_sample_prob <- df_all_repeats %>% 
  group_by(n_exp) %>% 
  dplyr::summarise(sample_prob = sum(success)/length(success)) %>% 
  ungroup()

# Назовем "ошибкой оценки вероятности" дисперсию выборочных вероятностей
prob_error <- sqrt(mean((df_sample_prob$sample_prob - true_prob)^2) )

# Посмотрим, как это выглядит на графике

ggplot(df_sample_prob, aes(x = sample_prob)) +
  geom_histogram(color = 'black', fill = 'white', binwidth = 0.01) +
  geom_vline(xintercept = true_prob, linetype = "dashed", colour = "red") +
  xlab(paste("Error =",round(prob_error,3))) + xlim(0,1) +
  theme_bw()
```

## Генерируем сразу много экспериментов

```{r multiple, echo=T, warning=T, error=T}

# Соберем все из двух предыдущих чанков в одну функцию

generate_prob_error <- function(n_patients, true_prob) {
  n_repeats = 1000
  
  df_all_repeats <- data.frame(
    n_exp = rep(1:n_repeats, each = n_patients),
    ID = rep(1:n_patients, n_repeats),
    success = rbinom(n_repeats*n_patients, 1, true_prob))

  df_sample_prob <- df_all_repeats %>% 
  group_by(n_exp) %>% 
  dplyr::summarise(sample_prob = sum(success)/length(success)) %>% 
  ungroup()

  prob_error <- sqrt(mean((df_sample_prob$sample_prob - true_prob)^2) )

  return(prob_error)
}


patients <- c(3,5,10,15,20,30,50,75,100,200,500,1000) # Объемы выборок
probs <- seq(0.1,0.9,0.1) # набор истинных вероятностей

# Сгенерируем одну большую табличку

prob_errors <- crossing(patients, probs) %>% 
  rowwise() %>%
  mutate(errors = generate_prob_error(patients, probs)) %>%
  ungroup

prob_errors_wide <- prob_errors %>% pivot_wider(names_from = probs, values_from = errors)

# Вообще, для наглядности было бы хорошо еще нарисовать графиков, но уже нет сил, прошу прощения. 
# Словесное описание найденных закономерностей см. в общем файле с решением ДЗ.
```
